feature/fetch-data: add NotesDataAPI class that handles fetching, storing and updating the data
popsilviu/notes-app pull request #3
Opened 2024-07-21 15:35 UTC by CozmaRares

2024-07-29 14:29 UTC, popsilviu requested changes

2024-07-29 14:29 UTC, popsilviu commented on src/fetch-data.js
> +function NoteWithDescriptionHTML(note) {
Look into using https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template, I may or may not remember if this is the correct usage for reusable HTML.

2024-07-29 14:29 UTC, popsilviu commented on src/fetch-data.js
> +function NoteWithDescriptionHTML(note) {
As a not this was nice of you to add but a bit beyond the scope of the ticket.

2024-07-29 14:29 UTC, popsilviu commented on src/fetch-data.js
> +// @ts-check
Please retain the JSdoc but loose the type checking, we don't need that for now and is not enforceable as we don't have a build pipeline for our project

2024-08-05 14:34 UTC, CozmaRares commented
added implementation for the tickets:
      - transmit create data to api
      - transmit update data to api
      - transmit delete data to api

2024-08-12 16:09 UTC, popsilviu approved these changes

2024-08-12 16:09 UTC, merged